database:
  - name: the_reserve
    databaseName: the-reserve
    user: postgres
    plan: free

services:
  - type: web
    name: the-reserve
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommnad: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: the_reserve
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false- key:WEB_CONCERRENCY
        value: 2