development:
  adapter: postgresql
  database: the_reserve_development
  username: postgres
  password: secret
  host: localhost

test:
  adapter: postgresql
  database: the_reserve_test
  username: postgres
  password: secret
  host: localhost

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000
  # Uncomment the following if you're using specific variables
  # username: <%= ENV['DATABASE_USERNAME'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # host: <%= ENV['DATABASE_HOST'] %>
  # port: 5432
