# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: the_reserve_development
  pool: 5
  username: postgres
  password: secret
  host: localhost

test:
  <<: *default
  database: the_reserve_test
  host: localhost
  port: 5432
  username: postgres
  password: secret

production:
  primary: &primary_production
    <<: *default
    database: the_reserve_production
    username: the_reserve
    password: <%= ENV["THE_RESERVE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: the_reserve_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: the_reserve_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: the_reserve_production_cable
    migrations_paths: db/cable_migrate
