development:
  adapter: postgresql
  database: the_reserve_development
  username: postgres
  password: secret
  host: 172.18.0.2  
  port: 5432

test:
  adapter: postgresql
  database: the_reserve_test
  username: postgres
  password: secret
  host: 172.18.0.2  
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
