default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: the_reserve_development
  username: postgres
  password: secret
  host: 172.18.0.2  
  port: 5432

test:
  adapter: postgresql
  database: the_reserve_test
  username: postgres
  password: secret
  host: 172.18.0.2  
  port: 5432

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
